### ISSUE TITLE
Package 'mysql-client' has no installation candidate

### ISSUE THREAD

**Issue by dxenes1** [aplbrain/saber#15]
CWLDockerfile and WebDockerfile fail to build when the `apt-get install mysql-client ` and `apt-get install mysql-server` lines are reached. Raises the following error:

```
E: Package 'mysql-client' has no installation candidate
E: Package 'mysql-server' has no installation candidate
```

**Comment by ssatyamchauhan** [comment]
I am also facing the same issue in Linux Parrot OS. Can anyone let me know, why is it so? I have also tried adding .deb package and ppt repo, but it's still not installing.

**Comment by j6k4m8** [comment]
@ssatyamchauhan make sure you've updated your aptitude repos with `apt update` or `apt-get update` and try again. If you are still having issues, it is likely a repo name difference (`mysqld` vs `mysql` etc).

 it is also possible that your repo name is just `mysql` rather than `mysql-client` on Parrot.

One final thing to check (let me know if it's still not working!) is if you already have an existing version of mysql on your OS; many linux flavors come with a mysql client, but it tends to be a bit out of date, and won't necessarily play nicely with your other software. If one already exists, you may need to uninstall it and reinstall the new version.
